//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proje.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class RANDEVU
    {
        public int RandevuID { get; set; }
        public Nullable<int> MusteriID { get; set; }
        public Nullable<int> SiparisID { get; set; }
    
        public virtual MUSTERI MUSTERI { get; set; }
        public virtual SIPARIS SIPARIS { get; set; }
    }
}
