//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proje.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class SIPARIS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SIPARIS()
        {
            this.FATURA = new HashSet<FATURA>();
            this.RANDEVU = new HashSet<RANDEVU>();
        }
    
        public int SiparisNo { get; set; }
        public Nullable<System.DateTime> SiparisTarihi { get; set; }
        public Nullable<decimal> ToplamTutar { get; set; }
        public Nullable<int> UrunID { get; set; }
        public Nullable<int> MusteriNo { get; set; }
        public Nullable<System.DateTime> Tarih { get; set; }
        public string SiparisDurum { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FATURA> FATURA { get; set; }
        public virtual MUSTERI MUSTERI { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RANDEVU> RANDEVU { get; set; }
        public virtual URUN URUN { get; set; }
    }
}
